### ISSUE TITLE
Crash on 1.21.3

### ISSUE THREAD

**Issue by globau** [LambdAurora/SpruceUI#56]
1.21.3 changed `DrawContext.drawTexture`'s signature, looks like it now needs `Function<Identifier, RenderLayer> renderLayers` (`RenderLayer::getGuiTextured` maybe?).

```
java.lang.NoSuchMethodError: 'void net.minecraft.client.gui.DrawContext.method_25290(net.minecraft.util.Identifier, int, int, float, float, int, int, int, int)'
	at knot//dev.lambdaurora.spruceui.widget.SpruceCheckboxWidget.renderBackground(SpruceCheckboxWidget.java:127)
	at knot//dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.render(AbstractSpruceWidget.java:265)
	at knot//dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.lambda$renderWidget$1(SpruceOptionListWidget.java:222)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at knot//dev.lambdaurora.spruceui.widget.container.SpruceOptionListWidget$OptionEntry.renderWidget(SpruceOptionListWidget.java:222)
	at knot//dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.render(AbstractSpruceWidget.java:266)
	at knot//dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.lambda$renderWidget$0(SpruceEntryListWidget.java:341)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at knot//dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.renderWidget(SpruceEntryListWidget.java:341)
	at knot//dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.render(AbstractSpruceWidget.java:266)
	at knot//dev.lambdaurora.spruceui.screen.SpruceScreen.renderWidgets(SpruceScreen.java:127)
	at knot//dev.lambdaurora.spruceui.screen.SpruceScreen.render(SpruceScreen.java:115)
	at knot//net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:113)
	at knot//net.minecraft.client.render.GameRenderer.mixinextras$bridge$renderWithTooltip$58(GameRenderer.java)
	at knot//net.minecraft.client.render.GameRenderer.wrapOperation$zni000$fabric-screen-api-v1$onRenderScreen(GameRenderer.java:1342)
	at knot//net.minecraft.client.render.GameRenderer.render(GameRenderer.java:510)
	at knot//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1335)
	at knot//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:930)
	at knot//net.minecraft.client.main.Main.main(Main.java:238)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by globau** [comment]
Oops, my bad.   Looks like this is fixed with v6.
